name: Build Docker

on:
  workflow_call:
    inputs:
      push: 
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      if: ${{ inputs.push }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Adjust tag for docker image
      id: tag
      run: |
        export TAG=$(echo "${{ github.ref_name }}" | tr -d "v" | tr "/" "-")
        echo "value=$TAG" >> "$GITHUB_OUTPUT"
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: ${{ inputs.push }}
        tags: ghcr.io/nu12/pdf:latest,ghcr.io/nu12/pdf:${{ steps.tag.outputs.value }}