name: CD
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.6

    - name: Create GH release
      env:
        GH_TOKEN: ${{ github.TOKEN }}
      run: |
        gh release create ${{ github.ref_name }}

  build-linux:
    name: Build
    needs: [release]
    uses: ./.github/workflows/build-linux.yml
    with:
      go-version: 1.20.6
      is-release: true
    secrets: inherit

  build-windows:
    name: Build
    needs: [release]
    uses: ./.github/workflows/build-windows.yml
    with:
      go-version: 1.20.6
      is-release: true
    secrets: inherit
    
  build-docker:
    name: Build
    needs: [release]
    uses: ./.github/workflows/build-docker.yml
    with:
      push: true
    secrets: inherit