name: CD
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.6

    - name: Create GH release
      env:
        GH_TOKEN: ${{ github.TOKEN }}
      run: |
        gh release create ${{ github.ref_name }}

  build-linux:
    name: Build Linux
    needs: [release]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/build/linux
      with:
        go-version: 1.20.6
        is-release: true

  build-windows:
    name: Build Windows
    needs: [release]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/build/windows
      with:
        go-version: 1.20.6
        is-release: true
    
  docker:
    name: Build Docker
    needs: [release]
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/docker/build
      with:
        push: true
    