name: CI
on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.6
    
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.53

    - name: Tests
      run: |
        go test -coverprofile cover.out -v ./...
        go tool cover -func=cover.out

  build-linux:
    name: Build
    needs: [test]
    uses: ./.github/workflows/build-linux.yml
    with:
      go-version: 1.20.6
      is-release: false
    secrets: inherit

  build-windows:
    name: Build
    needs: [test]
    uses: ./.github/workflows/build-windows.yml
    with:
      go-version: 1.20.6
      is-release: false
    secrets: inherit